export const events = [
  {
    title: "React Conf 2025",
    image: "/images/event1.png",
    slug: "react-conf-2025",
    location: "Las Vegas, Nevada",
    date: "May 14-15, 2025",
    time: "9:00 AM",
  },
  {
    title: "Next.js Conf 2025",
    image: "/images/event2.png",
    slug: "nextjs-conf-2025",
    location: "San Francisco, California",
    date: "June 18-19, 2025",
    time: "10:00 AM",
  },
  {
    title: "Node Summit 2025",
    image: "/images/event3.png",
    slug: "node-summit-2025",
    location: "Portland, Oregon",
    date: "July 22-23, 2025",
    time: "8:30 AM",
  },
  {
    title: "Web Summit Europe 2025",
    image: "/images/event4.png",
    slug: "web-summit-europe-2025",
    location: "Lisbon, Portugal",
    date: "November 3-5, 2025",
    time: "9:00 AM",
  },
  {
    title: "TypeScript Conference 2025",
    image: "/images/event5.png",
    slug: "typescript-conf-2025",
    location: "Austin, Texas",
    date: "August 12-13, 2025",
    time: "9:00 AM",
  },
  {
    title: "JavaScript Jam Hackathon",
    image: "/images/event6.png",
    slug: "js-jam-hackathon-2025",
    location: "New York, New York",
    date: "September 27-28, 2025",
    time: "11:00 AM",
  },
];
